clear stack;

define Vowel [a|i|u];
define Cons [b|d|h|g|k|l|m|n|p|r|t|w|y]; #doppelte rein oder raus

#morpho-phonemics:
define FinalL [l -> 0 || _ .#. r];

#Nouns: Case
#ErgInstr
define ErgInstrRU [A -> r || [l|u|a] _]; #auch bei stems ending in a (sagt die autorin aber nicht)
define ErgInstrNGU [A (->) n g || i _]; 
define ErgInstrNGGU [A -> n g g || i _]; 
define ErgInstrDel [A -> 0 || r r _]; 
define ErgInstrB [A -> b || m _]; #voiced statt voiceless genommen wie der autor
define ErgInstrD [A -> d || n _];
define ErgInstrDH [A -> d h || n h _]; 
define ErgInstrG [A -> g || n g _];
#AccH
define AccHN [B (->) n ];
define AccHDel [B -> 0];
#Loc
define LocVowel [C -> n g || Vowel _]; 
define LocL [C -> r || l _]; 
define LocDA [C -> d || [Cons - l] _ ];
#Abl
define AblNG [D -> n g || Vowel _]; 
define AblDel [D -> 0 || Cons _]; 


read regex FinalL .o. ErgInstrRU .o. ErgInstrNGU .o. ErgInstrNGGU 
.o. ErgInstrDel .o. ErgInstrB .o. ErgInstrD .o. ErgInstrDH
.o. ErgInstrG .o. AccHN .o. AccHDel .o. LocVowel .o. LocDA
.o. AblNG .o. AblDel;

read lexc < dharumbal-lex.txt;

compose net;

apply down < dharumbal-upper.txt;
#apply up < dharumbal-lower.txt;



#source dharumbal-test.script
#kasus hängt manchmal an adj -> nicht beachtet

